CREATE TABLE IF NOT EXISTS kpi_schedule_v3 (
  kpi_schedule_id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100),
  notes TEXT,
  type ENUM('PLANNING','ADJUSTMENT','MONITORING','CALIBRATION') NOT NULL,
  start_date DATE,
  end_date DATE,

  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
