CREATE TABLE IF NOT EXISTS tb_employee (
  employee_id int NOT NULL AUTO_INCREMENT,
  group_id int DEFAULT NULL,
  user_id int DEFAULT NULL,
  file_id int DEFAULT NULL,
  manager_id int DEFAULT NULL,
  coach_id int DEFAULT NULL,
  firstname varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  middlename varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  lastname varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  job_class_level varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  employee_number varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  old_employee_number varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  position_id_backup_8_nov int DEFAULT NULL,
  status_worker varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  archived_at timestamp NULL DEFAULT NULL,
  createdAt timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deletedAt timestamp NULL DEFAULT NULL,
  class varchar(5) DEFAULT NULL,
  period varchar(5) DEFAULT NULL,
  jabatan_id varchar(5) DEFAULT NULL,
  stat_jabatan varchar(5) DEFAULT NULL,
  unit_induk text,
  work_area varchar(255) DEFAULT NULL,
  work_unit text,
  penugasan varchar(255) DEFAULT NULL,
  cost_center varchar(255) DEFAULT NULL,
  active_status varchar(50) DEFAULT NULL,
  no_peg varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  gelar_akademik varchar(100) DEFAULT NULL,
  type varchar(100) DEFAULT NULL,
  learning_wallet bigint DEFAULT NULL,
  learning_wallet_is_freeze tinyint DEFAULT NULL,
  position_id int DEFAULT NULL,
  kj_definitif varchar(100) DEFAULT NULL,
  created_by int DEFAULT NULL COMMENT 'FK to tb_user.user_id',
  werks_new varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  pernr varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  company_id varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  wallet int DEFAULT NULL,
  old_job_class_level varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  employee_type varchar(50) DEFAULT NULL COMMENT 'organik, etc',
  corporate_email varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  PRIMARY KEY (employee_id),
  KEY tb_employee_group_id_IDX (group_id) USING BTREE,
  KEY tb_employee_user_id_IDX (user_id) USING BTREE,
  KEY tb_employee_position_id_IDX (position_id_backup_8_nov) USING BTREE,
  KEY tb_employee_employee_number_IDX (employee_number) USING BTREE,
  KEY tb_employee_old_employee_number_IDX (old_employee_number) USING BTREE,
  KEY idx_tb_employee_firstname (firstname),
  KEY idx_tb_employee_file_id (file_id),
  KEY idx_tb_employee_type (employee_type),
  KEY tb_employee_employee_id_index (employee_id),
  KEY idx_employee_lookup (employee_number,firstname)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
